<?php

declare(strict_types=1);

namespace Calisero\SymfonySms;

use Calisero\Sms\Dto\Account;
use Calisero\Sms\Dto\CreateMessageResponse;
use Calisero\Sms\Dto\CreateVerificationResponse;
use Calisero\Sms\Dto\GetMessageResponse;
use Calisero\Sms\Dto\GetVerificationResponse;
use Calisero\Sms\Dto\PaginatedMessages;
use Calisero\Sms\Exceptions\ApiException;

/**
 * Sends SMS messages and verification codes through the Calisero API.
 *
 * Autowire it by this interface; the bundle's implementation is the service
 * calisero.sms_client. The SDK's exceptions (\Calisero\Sms\Exceptions\ApiException and its
 * subclasses) report the API's refusals; an \InvalidArgumentException or a
 * \RuntimeException reports a missing parameter or configuration before any request.
 */
interface SmsClientInterface
{
    /**
     * Send an SMS message.
     *
     * Parameters (the optional ones also in camelCase: visibleBody, scheduleAt...):
     *  - to (string, required): the recipient, in E.164 format
     *  - text (string, required): the message body
     *  - from (string): an approved sender ID
     *  - visible_body (string): the body shown in the dashboard and the API instead of the text
     *  - validity (int): the validity period, in hours
     *  - schedule_at (\DateTimeInterface, or a 'Y-m-d H:i:s' string in Romania time)
     *  - callback_url (string): where Calisero posts the delivery status, instead of the bundle's webhook
     *  - shorten_urls (bool): replace the links of the text with short ones
     *
     * @param array<string, mixed> $params
     *
     * @throws \InvalidArgumentException when a parameter is missing, unknown or of the wrong type
     * @throws ApiException              when the API refuses the message or does not answer
     */
    public function sendSms(array $params): CreateMessageResponse;

    /**
     * The configured account (calisero.account_id): credit, status and daily sending limit.
     *
     * @throws \RuntimeException when calisero.account_id is not configured
     * @throws ApiException      when the API refuses the request or does not answer
     */
    public function getAccount(): Account;

    /**
     * The configured account's credit.
     *
     * @throws \RuntimeException when calisero.account_id is not configured
     * @throws ApiException      when the API refuses the request or does not answer
     */
    public function getBalance(): float;

    /**
     * A message, with its delivery status and the click counts of its shortened links.
     *
     * @throws ApiException when the API refuses the request or does not answer
     */
    public function getMessageStatus(string $messageId): GetMessageResponse;

    /**
     * The messages, a page at a time.
     *
     * @throws ApiException when the API refuses the request or does not answer
     */
    public function listMessages(int $page = 1): PaginatedMessages;

    /**
     * Delete a message, which only a message not yet sent allows.
     *
     * @throws ApiException when the API refuses the request or does not answer
     */
    public function deleteMessage(string $messageId): void;

    /**
     * Send a verification code, generated by Calisero, to a phone number.
     *
     * Parameters: to (or phone, required), brand, template (containing {code}),
     * expires_in (or expiresIn, minutes). Either brand or template is required.
     *
     * @param array<string, mixed> $params
     *
     * @throws \InvalidArgumentException when a parameter is missing, unknown or of the wrong type
     * @throws ApiException              when the API refuses the code or does not answer
     */
    public function sendVerification(array $params): CreateVerificationResponse;

    /**
     * Check a verification code: its status is 'verified' when the code was right.
     *
     * Parameters: to (or phone, required), code (required).
     *
     * @param array<string, mixed> $params
     *
     * @throws \InvalidArgumentException when a parameter is missing, unknown or of the wrong type
     * @throws ApiException              when the API refuses the code (a 422 for a wrong or expired one) or does not answer
     */
    public function checkVerification(array $params): GetVerificationResponse;
}
